### ISSUE TITLE
build fails on macOS when calling for "emplace"

### ISSUE THREAD

**Issue by hpckurt** [MilchRatchet/PSArcInterface#5]
Hi!

I ran into an issue trying to compile on macOS 15.1 Sequoia:

```
[  3%] Building CXX object libpsarc/CMakeFiles/Shared.dir/src/psarc_archive.cpp.o
/Users/hpckurt/Downloads/PSArcInterface/libpsarc/src/psarc_archive.cpp:67:27: error: no matching member function for call to 'emplace'
  this->uncompressedBytes.emplace(std::vector<byte>());
  ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/optional:947:5: note: candidate template ignored: requirement 'is_constructible_v<PSArc::FileData, std::vector<unsigned char, std::allocator<unsigned char>>>' was not satisfied [with _Args = <std::vector<unsigned char>>]
    emplace(_Args&&... __args)
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk/usr/include/c++/v1/optional:962:5: note: candidate template ignored: could not match 'initializer_list' against 'vector'
    emplace(initializer_list<_Up> __il, _Args&&... __args)
    ^
1 error generated.
make[2]: *** [libpsarc/CMakeFiles/Shared.dir/src/psarc_archive.cpp.o] Error 1
make[1]: *** [libpsarc/CMakeFiles/Shared.dir/all] Error 2
make: *** [all] Error 2
```

I'm using the default Xcode clang.

I understand if macOS is outside what you're willing to support, but I thought I may as well open the issue :)

**Comment by MilchRatchet** [comment]
Hi,

I personally don't have access to a Mac so I cannot directly support it. However, I can add a build job to the CI to make sure that it atleast builds on Mac. I will look to fix these compile issues and get back to you then but obviously I will not be able to guarantee that it works correctly.

**Comment by hpckurt** [comment]
Awesome! Thanks!

**Comment by MilchRatchet** [comment]
I have fixed the compilation issues on MacOS, or atleast it builds on the CI now which runs on Sonoma. Let me know if there are any more issues. I would also like to here if it runs at all.

**Comment by hpckurt** [comment]
@MilchRatchet Just as an update, it seems to be working for the most part! It extracts files 90% of the time just fine, but sometimes it will just fail to extract properly.

Every file extracted has the error message `Fatal Error in decompression: Encountered unhandled ZLIB error code (-3).`

But that doesn't necessarily seem to affect anything. Sometimes files are extracted as zero byte files, but it seems random.
